### ISSUE TITLE
Add a confirmation popup when transferring tokens

### ISSUE THREAD

**Issue by OlhaD** [Greenstand/treetracker-wallet-admin-client#101]
When the user transfers money from one wallet to another, he/she should see a confirmation dialog.

![image](https://github.com/Greenstand/treetracker-wallet-admin-client/assets/19413810/d318e4e0-5671-4f6d-9542-3dd0d7b7ab73)

**Comment by devham236** [comment]
Hey @OlhaD, is there a link to the application or a short demo video so i can see how it works and looks?
