### ISSUE TITLE
Wallet Home page: header

### ISSUE THREAD

**Issue by OlhaD** [Greenstand/treetracker-wallet-admin-client#13]
**Description**: As a logged-in wallet admin user, I want to be able to see the wallet home page so that I can view information about my wallet.

**Acceptance Criteria**:
After logging in, the user should be directed to the wallet home page.
The wallet home page should display the logo of the wallet at the top of the page.
The wallet home page should display the name of the wallet at the top of the page.
The wallet home page should display the number of tokens which are in the process of transferring.
~~The wallet home page should display the text block with information about the wallet.~~

**Comment by pranavkparti** [comment]
Hello, can I be assigned to this issue?
