### ISSUE TITLE
Create an error page for 404 - Page Not Found error

### ISSUE THREAD

**Issue by OlhaD** [Greenstand/treetracker-wallet-admin-client#19]
The page should be displayed when a user enters a URL which doesn't exists, like {host}/some-wrong-URL.
The page should have an error message: "Oops! We can't find the page you're looking for. Please check the URL or return to the homepage.". This text is just an idea, you are welcome to provide a better idea.

**Comment by parag477** [comment]
I want to work on this issue. Can you please assign this to me?

**Comment by ajay2827** [comment]
@OlhaD if this issue hasn't solved till now, can you please assign this issue to me
