### ISSUE TITLE
Wallet Home page: information about the wallet

### ISSUE THREAD

**Issue by OlhaD** [Greenstand/treetracker-wallet-admin-client#23]
Description: As a logged-in wallet admin user, I want to see the wallet description.

Acceptance Criteria:
The wallet home page should display the text block with information about the wallet.

Web Map API should be used. TBD: which exactly.

**Comment by garenpham** [comment]
Are you talking about the Wallet Home page: header? If not, please specify where I can find the design in the user stories document.

**Comment by garenpham** [comment]
Can I work on this issue? Do you have the dummy data to put in the text blocks yet? Is this task requires creating the remaining 5 info blocks on the Wallet home page?

**Comment by pranavkparti** [comment]
@OlhaD it might be from `treetracker-query-api` in fact. Looking at the API schema, it seems that the `/organizations/{id}` endpoint is supposed to return an object with `about` and `mission` fields, which is not yet implemented. I hope this is what you're referring to?
- Query API spec - https://github.com/Greenstand/treetracker-query-api/blob/main/docs/api/spec/query-api.yaml
- An example of what the endpoint returns: https://dev-k8s.treetracker.org/query/v2/organizations/f6d19e49-2d1a-4c1a-90d1-8f651bdaeaa5

**Comment by pranavkparti** [comment]
A correction: looking at the wallet table schema, it seems there is an `about` field already present. The API get endpoint should simply be extended to return this field.
