### ISSUE TITLE
Main Menu V1

### ISSUE THREAD

**Issue by stvgreen1** [Greenstand/treetracker-wallet-admin-client#26]
Description: As a wallet admin user, I want to be able to access all the pages and functionality provided by the application and logout. Here display the Home Page and Send tokens page.

Acceptance Criteria:
The menu should display Greenstand logo that should redirect to home page.
The menu should display an item for Home page with “Home” logo and denomination that redirect to home page.
The menu should display an item for Send Tokens Page with the “Send Tokens” logo and denomination that redirects to Send Tokens Page.
The menu should display a button “☰” that enable the user to toggle the menu.
The menu should display an item for the list of transfers with the “My Transfers” logo and denomination that redirects to the corresponding page.
 
Link to user stories document (Attached images are still being updated. The acceptance criterias must be met.):
https://docs.google.com/document/d/1IF4fe4_BC319aoBKBW5LV2pypyDTy4K8qe1qqHexQ1Y/edit#heading=h.b57wy8cd5ys7

Release: V1

**Comment by garenpham** [comment]
Good evening, can you assign me to work on this issue, please?

**Comment by stvgreen1** [comment]
@garenpham the "Transfers List" menu item and page has been renamed to  "My Transfers"

**Comment by garenpham** [comment]
@stvgreen1 Got it!
