### ISSUE TITLE
Send Tokens Page V1: block “Display Available Tokens”

### ISSUE THREAD

**Issue by stvgreen1** [Greenstand/treetracker-wallet-admin-client#27]
Description: As a logged-in wallet admin user, I want to be able to see the amount of available tokens.
Acceptance Criteria:
The Send Tokens Page should display the UI block with a number of how many tokens are available in the wallet.
 

Link to user stories document: https://docs.google.com/document/d/1IF4fe4_BC319aoBKBW5LV2pypyDTy4K8qe1qqHexQ1Y/edit#heading=h.b57wy8cd5ys7

**Note: Attached images are still being updated.  The acceptance criterias must be met over the design.**

Release: V1

**Comment by pranavkparti** [comment]
I can work on this.
