### ISSUE TITLE
Define MVP

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-wallet-admin-client#4]
The MVP should include the minimum functionality to make this tool useful on the first release.

All tickets should be logged against the first release of this product or later releases.

**Comment by Davidezrajay** [comment]
hese are ideas for milestone and releases.

MVP -Release v1

Login
Milestone - see tokens in wallet handle logged into
Milestone - select number of tokens in wallet
Milestone - send tokens to other wallet wallet
V2
Milestone - filter tokens using admin filters
Milestone - See wallet handles that your login has managed or (sub-wallets) rights to
Milestone - create new wallets

V3
Milestone - See transfer status
Milestone - See wallet trust relationships

V4
Milestone: See # regions
Milestone :See # planters in wallet
Milestone - Login in self-managed wallet (dependency - keyclock)

V5
Explore available tokens
Buy /request tokens from other wallet

**Comment by dadiorchen** [comment]
Just an off-topic, how about this workflow to send to someone:
prerequisites: we know the one's email address:
Pick tokens and input the email address and submit --> the guy receive an email --> click the URL and jump to the registration page (by Keycloak) --> finish the registration --> system creates the wallet for her/him --> token was transferred to his/her wallet.

**Comment by Davidezrajay** [comment]
@dadiorchen, this seems correct. 
@stvgreen1 Can we add this to pipeline.
Although, I'd guess it goes in V4.
