### ISSUE TITLE
Remove mocked data related to the Login and the Wallet

### ISSUE THREAD

**Issue by OlhaD** [Greenstand/treetracker-wallet-admin-client#44]
1) Check all // TODO comments in the code
2) apiClient.js - remove the hardcoded token from the real one we got from auth API
3) Wallet.js - if we decode the token we got from auth API, we can get a Wallet ID from the payload. This ID should replace the mocked one.

**Comment by stvgreen1** [comment]
@OlhaD Yes please no hardcoded token. Please make sure you retrieve the token from the api and handle it in a standard way. And this works in all the environment including (local, dev, test, prod …)

Please make sure also for the walletId you get it in the standard way.

**Comment by OlhaD** [comment]
PR: https://github.com/Greenstand/treetracker-wallet-admin-client/pull/54
