### ISSUE TITLE
Link User Story from the Readme in this Repo

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-wallet-admin-client#5]
Current users stories written here: https://docs.google.com/document/d/1IF4fe4_BC319aoBKBW5LV2pypyDTy4K8qe1qqHexQ1Y/edit#heading=h.b57wy8cd5ys7

**Comment by OlhaD** [comment]
@sebastiangaertner Please, mark this PR as reviewed so I can merge it and close this issue: https://github.com/Greenstand/treetracker-wallet-admin-client/pull/9

**Comment by Davidezrajay** [comment]
Thanks olhaD.. super exciting to have this going
