### ISSUE TITLE
Define Milestone

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-wallet-admin-client#7]
These are ideas for milestone and releases. 

**MVP -Release v1**
- Login 
Milestone - see tokens in wallet handle logged into
Milestone - select number of tokens in wallet 
Milestone - send tokens to other wallet wallet

V2 
Milestone - filter tokens using admin filters
Milestone - See wallet handles that your login has managed or (sub-wallets) rights to
Milestone - create new wallets

V3 
Milestone - See transfer status
Milestone - See wallet trust relationships

V4 
Milestone: See # regions
Milestone :See # planters in wallet
Milestone - Login in self-managed wallet (dependency - keyclock)

V5
Explore available tokens 
Buy /request tokens from other wallet

**Comment by sebastiangaertner** [comment]
These are ideas for milestone and releases.

MVP -Release v1

Login
Milestone - see tokens in wallet handle logged into
Milestone - select number of tokens in wallet
Milestone - send tokens to other wallet wallet
Milestone - See wallet handles that your login has managed or (sub-wallets) rights to
Milestone - create new wallets
Milestone - See transfer status
Milestone - See wallet trust relationships

V2
Milestone - filter tokens using admin filters

V3
Milestone: See # regions
Milestone :See # planters in wallet
Milestone - Login in self-managed wallet (dependency - keyclock)

V4
Explore available tokens
Buy /request tokens from other wallet

**Comment by Davidezrajay** [comment]
@stvgreen1 
The only thing that V1 doesn't have that seems critical is a "sign up"
Which would have a user story of, "User goes to URL, clicks create an account, creates an account and chooses wallet handle."

**Comment by dadiorchen** [comment]
@OlhaD I think we can go for the login with current wallet API, then the next step is bringing in the Keycloak, use it to handle the login, registration, user profile, password change, forgot password, so when reaching to that, we will get a unified single-sign-on.
