### ISSUE TITLE
Create Sub wallets

### ISSUE THREAD

**Issue by stvgreen1** [Greenstand/treetracker-wallet-admin-client#98]
Name: Create Sub Wallet
Description: As a logged-in wallet admin user, I want to create a new sub (managed) wallet.
 
Acceptance Criteria:
There should be a create new button at the top of the “Managed Wallets List” Page
Whenever the user click the create new wallet button in the “Managed Wallets List” Page a dialog with a form to create the wallet should appear.
The dialog should contain an input field with the wallet name.
There should be a create button. When the button is clicked, the wallet is created and the window is closed. A success notification message appears.
There should be a cancel button, as well as a close button to close the window without creating any wallet.
There should be an error notification if a wallet with this name already exists or if the name is not convenient (special characters).
Any error during the creation should be notified to the user

Link to user stories document: https://docs.google.com/document/d/1IF4fe4_BC319aoBKBW5LV2pypyDTy4K8qe1qqHexQ1Y/edit#heading=h.b57wy8cd5ys7

**Comment by OlhaD** [comment]
@pranavkparti Please, create a PR with this functionality as-is, I will merge it to the Wallets list page myself as soon as it is ready.
